/* Le mot de passe est toujours défini comme : Azerty12 (respecter la casse) */
INSERT INTO projet_tutore_web.users (last_name, first_name, password, street_name, zip_code, district, city, mobile_number, email_address) VALUES ('FRAPPIER', 'Mayhew', '$argon2id$v=19$m=65536,t=4,p=1$VkNXRHNRTW8wMVNFZC5HVQ$dkVFak6nwknIbxSDEoGt5qsH4GkhToSWAn+mAzD7jUU', '71, Rue De La Pompe', 91100, 'Fond Mondétour', 'ORSAY', 433603785, 'mayhewfrappier@teleworm.us');
INSERT INTO projet_tutore_web.users (last_name, first_name, password, street_name, zip_code, district, city, mobile_number, email_address) VALUES ('ESPERANZA', 'Brunelle', '$argon2id$v=19$m=65536,t=4,p=1$OS5CU1VMYm9hUi8yb3Y4aQ$6LmJrnkhGc+ms9Np4EerK1buqagdgkGmdHo2B5aVp18', '37, Rue Gontier-Patin', 91110, 'Fond Mondétour', 'ORSAY', 484713132, 'esperanzabrunelle@armyspy.com');
INSERT INTO projet_tutore_web.users (last_name, first_name, password, street_name, zip_code, district, city, mobile_number, email_address) VALUES ('BLONDLOT', 'Ormazd', '$argon2id$v=19$m=65536,t=4,p=1$UkxreVdxQmJGcDYzVlpFTQ$p6Y3FFKrcvWu16bTo5Gh6uERn7RfQfBKKIl7n7R/zUM', '97, Avenue Du Marechal Juin', 91110, 'Haut Mondétour', 'ORSAY', 214749174, 'ormazdblondlot@teleworm.us');
INSERT INTO projet_tutore_web.users (last_name, first_name, password, street_name, zip_code, district, city, mobile_number, email_address) VALUES ('LALONDE', 'Thomas', '$argon2id$v=19$m=65536,t=4,p=1$aTQ1TjgvMHEwMk5uM0x2Tg$Fr84Z5yF/ElszgSLem4oT7DxfH6gNpbZd7Mk9m7Ch/s', '69, Rue Des Dunes', 91110, 'Haut Mondétour', 'ORSAY', 557683233, 'thomaslalonde@armyspy.com');
INSERT INTO projet_tutore_web.users (last_name, first_name, password, street_name, zip_code, district, city, mobile_number, email_address) VALUES ('OLIVIER', 'Pomerleau', '$argon2id$v=19$m=65536,t=4,p=1$Zi9CYi5US0RIUXkvenEyaQ$P5Yr1jXucGsP+zIQTxoWK9D+fCcGjUvxCirOyAG0mng', '58, Boulevard De Prague', 91110, 'Haut Guichet Centre Ouest', 'ORSAY', 415671189, 'olivierpomerleau@rhyta.com');

/* Quelques légumes */
INSERT INTO projet_tutore_web.products (label, type, classification, description, price, season, unit) VALUES ('Concombre', 'Légumes', 'Cucurbitacées', 'Le concombre, comme le cornichon, est issu d’une plante potagère rampante qui appartient à la très grande famille des cucurbitacées, celle des courges. Autrefois, le concombre était ramassé à sa maturité, tandis que le petit frère, le cornichon, l’était avant qu’il ne grandisse. Des hybrides de la plante ont été créés, les uns produisant des concombres, les autres des cornichons, sans que l’on ait besoin de guetter leur taille pour les récolter. On en a profité en même temps pour accentuer leurs différences, non seulement de taille mais aussi de texture et de saveur. Mais ils sont pour la plupart verts et allongés.', 0.95, 'Printemps', 'À la pièce');
INSERT INTO projet_tutore_web.products (label, type, classification, description, price, season, unit) VALUES ('Artichaut', 'Légumes', 'Composées', 'Le nom désigne à la fois la plante entière, dérivée du chardon originaire de Méditerranée, et sa partie comestible. Celle-ci est le bouton de la fleur de la plante ; elle est formée d’un réceptacle, le « fond », qui est charnu. Il est entouré de bractées, que l’on nomme (à tort) les « feuilles ». Leur base est également charnue. Sur le fond se trouve le « foin », qui n’est pas comestible et qui donnera naissance à la fleur si l’artichaut n’est pas récolté.

Introduit en France par Catherine de Médicis, qui en était très friande, il devint ensuite populaire en Espagne. Puis il gagna l’Amérique, importé par les Français en Louisiane et par les Espagnols en Californie. L’artichaut a besoin de chaleur pour sa culture. 90 % de sa production mondiale vient des pays méditerranéens. Le reste se répartit entre l’Argentine, la Californie, la Nouvelle-Zélande, le Chili, le Venezuela et le Pérou.', 1.7, 'Printemps', 'À la pièce');
INSERT INTO projet_tutore_web.products (label, type, classification, description, price, season, unit) VALUES ('Carottes', 'Légumes', 'Ombellifères', 'Le terme « carotte » désigne aussi bien la plante potagère que le tubercule, plus ou moins allongé, qu’elle fournit et qui est consommé comme légume. La carotte est cultivée dans toutes les zones tempérées de la planète.

La carotte serait originaire d’Asie Mineure, où elle poussait déjà à l’état sauvage. Les anciens en consommaient surtout pour leur pouvoir de renforcer l’acuité visuelle, mais ils n’appréciaient pas vraiment ce légume. Pline la mentionne sous le nom de Pasticana galtica. Cette appellation existe encore dans certaines régions de France où la « pastenade » désigne la carotte. Autour du Xe siècle, la carotte fut domestiquée, dans les régions d’Asie centrale. Elle était souvent violette ou jaune. Au XIIIe siècle et dans l’Ouest, la carotte semble avoir été une plante aromatique. Elle commença à être cultivée comme légume au XVe siècle, où elle était alors surtout jaune. Au XVIe siècle, la carotte orange apparut, issue d’un croisement de carotte jaune et de carotte rouge effectué par les Hollandais, qui voulaient ainsi prouver leur fidélité à la Maison d’Orange, principauté protestante de France. Elle supplanta vite toutes les autres. La carotte européenne fut importée sur le continent américain durant la deuxième moitié du XVIe siècle, probablement en 1565. Vite adoptée par les Amérindiens, elle ne devint vraiment populaire aux États-Unis qu’au début du XXe siècle, après la découverte du carotène. Elle y est devenue l’un des légumes les plus cultivés à cause de l’intensive consommation de jus de carotte que font les Américains.', 1.55, 'Toute l''année', 'Le kilo');
INSERT INTO projet_tutore_web.products (label, type, classification, description, price, season, unit) VALUES ('Poireau', 'Légumes', 'Liliacées', 'Le poireau, souvent surnommé « l‘asperge du pauvre », est une plante potagère de la famille des Alliacées (ou Liliacées), la même que celle de l''ail, de l''oignon etc. Formé de feuilles enroulées étroitement les unes sur les autres, sa partie souterraine, appelée blanc de poireau, est tendre et la plus appréciée, tandis que ses feuilles vertes du haut sont dures et moins utilisées.
En France, au Moyen Âge, le poireau était fort estimé. La soupe la plus connue d''alors était le "porée", à base de feuilles vertes hachées menues. Jean Goeurot, médecin de François 1er, recommandait de manger des poireaux aux gens "mugueteurs de dames pour leur donner plaisante haleine" ! Mais alors, le poireau était surtout prescrit pour favoriser la diurèse, relâcher le ventre, arrêter les éructations, combattre les "suffocations utérines", augmenter le lait des nourrices, faire cesser les stérilités. Il est arrivé en Amérique du Nord avec les colons qui le cultivèrent dès la fin du 18e siècle, mais il n''y prendra jamais une très grande place dans la cuisine, de même qu''en Asie.', 1.9, 'Toute l''année', 'Le kilo');
INSERT INTO projet_tutore_web.products (label, type, classification, description, price, season, unit) VALUES ('Fève', 'Légumes', 'Légumineuses', 'La fève est une plante méditerranéenne très robuste, mesurant jusqu’à 1 m de hauteur. Ses fleurs, blanches, donnent des fruits en forme de longues gousses. Celles-ci sont tapissées d’une pellicule blanche et humide. Elles contiennent plusieurs graines vertes de forme ovale et aplatie qui portent le même nom que la plante. Au Québec, elles se nomment « fèves des marais » ou encore « gourganes ». Ces graines sont revêtues d’une peau assez épaisse.', 3.65, 'Été', 'Le kilo');
INSERT INTO projet_tutore_web.products (label, type, classification, description, price, season, unit) VALUES ('Épinard', 'Légumes', 'Chénopodiacées', 'L’épinard est une plante potagère à croissance rapide dont on consomme les feuilles, toujours vert foncé et lisses ou cloquées. Selon les variétés, elle est annuelle ou bisannuelle.
L’épinard est cultivé dans toutes les régions tempérées. En France, différentes variétés existent, qui couvrent ainsi le marché toute l’année.
Épinards d’automne/hiver : géant d’hiver, monstrueux de Viroflay, samos. Leurs feuilles sont grandes et bien drues.
Épinards de printemps/été : géant d’été, viking, junius. Leurs feuilles sont très tendres et fines.
En Asie, les épinards d’eau (ong choy en chinois, kangkung en indonésien) poussent dans l’eau des étangs. Au Japon, le horenso est une variété à petites feuilles, tendres et douces. La tétragone, aussi appelée épinard de Nouvelle-Zélande ou épinard d’été, est proche de l’épinard, mais elle n’appartient pas à la même famille. Ses feuilles sont plus charnues..', 2.59, 'Toute l''année', 'Le kilo');
INSERT INTO projet_tutore_web.products (label, type, classification, description, price, season, unit) VALUES ('Aubergine', 'Légumes', 'Solanacées', 'Icône de la cuisine méditerranéenne, l''aubergine fait partie de ces aliments caméléons qui s''apprêtent de mille et une façons. Fruit consommé comme légume, l''aubergine compte plusieurs variétés même si la violette reste la plus répandue en France. Sa forme oblongue et sa jolie couleur pourpre font de l''aubergine un légume populaire, apprécié et ce, grâce à son côté charnu, sa chair subtile et goûteuse.', 0.98, 'Été', 'Le kilo');
INSERT INTO projet_tutore_web.products (label, type, classification, description, price, season, unit) VALUES ('Radis rose', 'Légumes', 'Crucifères', 'Le radis rose est un légume-racine à chair blanche dont la couleur de la peau et la forme peuvent changer. Certaines variétés présentent une racine ronde, d’autres une racine allongée avec des couleurs allant du blanc rosé au rouge écarlate. Ce légume subtilement piquant qui se consomme aussi bien cru que cuit. Les fanes de radis sont comestibles et offrent de multiples possibilités culinaires.', 1.19, 'Toute l''année', 'Le kilo');
INSERT INTO projet_tutore_web.products (label, type, classification, description, price, season, unit) VALUES ('Mâche', 'Légumes', 'Autres', 'Plante herbacée aux petites feuilles vertes et tendres, réunies en bouquets appelés « rosettes », de saveur très douce, la mâche porte de nombreux autres noms selon les régions : blanchette, clairette, doucette, herbe des chanoines. Elle peut pousser à l’état sauvage mais est aussi cultivée.', 0.99, 'Hiver', 'Le kilo');
INSERT INTO projet_tutore_web.products (label, type, classification, description, price, season, unit) VALUES ('Crosne', 'Légumes', 'Labiées', 'Les tubercules prennent une forme de chapelet à cause des boursouflures successives. Ils ont un goût de noisette légèrement sucré, voisin du salsifis ou de l''artichaut. Ils se gardent plusieurs jours dans le bac à légumes et peuvent être congelés. Ils peuvent être confits dans le vinaigre.', 20, 'Hiver', 'Le kilo');

/* Les stocks */
INSERT INTO projet_tutore_web.`products.inventory` (id_product, quantity, discount_rate) VALUES (1, 10, 1);
INSERT INTO projet_tutore_web.`products.inventory` (id_product, quantity, discount_rate) VALUES (2, 50, 2);
INSERT INTO projet_tutore_web.`products.inventory` (id_product, quantity, discount_rate) VALUES (3, 100, 3);
INSERT INTO projet_tutore_web.`products.inventory` (id_product, quantity, discount_rate) VALUES (4, 10, 0);
INSERT INTO projet_tutore_web.`products.inventory` (id_product, quantity, discount_rate) VALUES (5, 1000, 1);
INSERT INTO projet_tutore_web.`products.inventory` (id_product, quantity, discount_rate) VALUES (6, 25, 0);
INSERT INTO projet_tutore_web.`products.inventory` (id_product, quantity, discount_rate) VALUES (7, 0, 0);
INSERT INTO projet_tutore_web.`products.inventory` (id_product, quantity, discount_rate) VALUES (8, 100, 0);
INSERT INTO projet_tutore_web.`products.inventory` (id_product, quantity, discount_rate) VALUES (9, 5, 0);
INSERT INTO projet_tutore_web.`products.inventory` (id_product, quantity, discount_rate) VALUES (10, 2, 0);

